fdfs:
  # 链接超时
  connect-timeout: 1501
  # 读取时间
  so-timeout: 601
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150

  tracker-list:
    - 192.168.168.22:22122


server:
  port: 7010
spring:
  application:
    name: ware-fast-dfs
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB